# Generated by Django 3.1.7 on 2021-03-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil', verbose_name='Imagen de perfil'),
        ),
    ]
